---
- name: Install build-essential
  apt: pkg=build-essential

- name: Get SBCL
  get_url: url=http://downloads.sourceforge.net/project/sbcl/sbcl/1.2.0/sbcl-1.2.0-x86-64-linux-binary.tar.bz2 dest=/tmp/sbcl-1.2.0-x86-64-linux-binary.tar.bz2
 
- name: Unarchive SBCL
  command: chdir=/tmp tar xvf /tmp/sbcl-1.2.0-x86-64-linux-binary.tar.bz2
 
- name: Install SBCL
  command: chdir=/tmp/sbcl-1.2.0-x86-64-linux sh install.sh
 
- name: Get Quicklisp
  get_url: url=http://beta.quicklisp.org/quicklisp.lisp dest=/tmp/quicklisp.lisp mode=0440
  sudo: false

- name: Install Quicklisp
  command: sbcl --non-interactive --load /tmp/quicklisp.lisp --eval '(quicklisp-quickstart:install)' creates=~/quicklisp
  sudo: false
 
- name: Copy .sbclrc
  copy: src=sbclrc dest=~/.sbclrc mode=644 force=no
  sudo: false

- name: Install Caveman2
  command: sbcl --non-interactive --eval '(ql:quickload :caveman2)'
  sudo: false

- name: Install Integral
#  command: sbcl --non-interactive --eval '(ql:quickload :integral)'
  git: repo=https://github.com/fukamachi/integral dest=~/quicklisp/local-projects/integral
  sudo: false

- name: Remove Integral README (since has ASCII stream decoding error)
  file: path=~/quicklisp/local-projects/integral/README.markdown state=absent
  sudo: false

- name: Install shelly
  shell: curl -L http://shlyfile.org/shly | LISP_IMPL=sbcl perl - install
  sudo: false

- name: Add SBCL_HOME
  lineinfile: dest=~/.bashrc regexp=^SBCL_HOME line="export SBCL_HOME=/usr/local/lib/sbcl" state=present
  sudo: false

- name: Add shelly to PATH
  lineinfile: dest=~/.bashrc regexp=shelly line="export PATH=$PATH:$HOME/.shelly/bin" state=present
  sudo: false

- name: Comment out line which prevents loading bash profile by ssh
  lineinfile: dest=~/.bashrc regexp='[ -z "$PS1" ] && return' line='# [ -z "$PS1" ] && return' state=present
  sudo: false

